version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/warehouse_db"
      SECRET_KEY: "your_secret_key"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - wms-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:5000"
    volumes:
      - ./frontend:/app
    networks:
      - wms-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wms-network

volumes:
  postgres-data:

networks:
  wms-network:
    driver: bridge
